# Generated by Django 3.0.6 on 2020-10-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='totalAmount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
